name: Run Solutions

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: uv sync
    - name: Run solutions
      run: make run-all
    - name: Create Comparison Table
      run: make comp-table
    - name: Commit results
      run: |
        git config --global user.email "leo@dumbartonserum.com"
        git config --global user.name "Leo Dumbarton"
        git add runs && git commit -m "update results" && git push
